title: Eliška Kotková
logo: image/46441148_10213189426752388_2290067478371368960_n-modified.png
description: QA Test Analyst | QA automation Tester | Test Engineer
show downloads: true
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-them
