title: Eliška Kotková
logo: image/IMG_0441_circled.png
description: QA Test Analyst | QA automation Tester | QA Test Engineer
show downloads: true
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-them
